### ISSUE TITLE
bug in  get_token() method in browser_calls_flask/views.py

### ISSUE THREAD

**Issue by franzi31** [TwilioDevEd/browser-calls-flask#6]
I'm new to github and python, so apologies in advance if I'm not doing something correctly.

on line  56, it looks like the generate method does not exist:

# Generate the capability token
token = capability.generate()

should it be like called like this?
token = capability._generate_payload()

**Comment by Kannanravindran** [comment]
@franzi31 Even I am having the same issue. but private methods are not meant to be called from an object. Also it won't work even if we use
`token = capability._generate_payload()`
it returns,
`{'scope': 'scope:client:outgoing?appSid=APxxxxxxxxxxxxxxxxxxxxxxx&clientName=support_agent scope:client:incoming?clientName=support_agent'}`

Hope there is a solution provided for this sooner.

**Comment by Kannanravindran** [comment]
@franzi31 I found a workaround to make this work.

Downgrade the twilio package:
`pip install twilio==5.7`

replace the `/browser_calls_flask/views.py` with the following code:
```
from flask import render_template, flash, jsonify, request
from . import app, db
from .forms import SupportTicketForm
from .models import SupportTicket

from twilio.util import TwilioCapability
from twilio import twiml


@app.route('/')
def root():
    form = SupportTicketForm()
    return render_template('home.html', form=form)


@app.route('/tickets', methods=['GET', 'POST'])
def new_ticket():
    success_message = "Your ticket was submitted! An agent will call you soon."
    form = SupportTicketForm()

    if form.validate_on_submit():
        ticket = SupportTicket(**form.data)
        db.session.add(ticket)
        db.session.commit()
        flash(success_message)
    return render_template('home.html', form=form)


@app.route('/dashboard', methods=['GET'])
def dashboard():
    support_tickets = SupportTicket.query.all()
    return render_template('support_dashboard.html', support_tickets=support_tickets)


@app.route('/support/token', methods=['GET'])
def get_token():
    """Returns a Twilio Client token"""
    # Create a TwilioCapability object with our Twilio API credentials
    capability = TwilioCapability(
        app.config['TWILIO_ACCOUNT_SID'],
        app.config['TWILIO_AUTH_TOKEN'])

    # Allow our users to make outgoing calls with Twilio Client
    capability.allow_client_outgoing(app.config['TWIML_APPLICATION_SID'])

    # If the user is on the support dashboard page, we allow them to accept
    # incoming calls to "support_agent"
    # (in a real app we would also require the user to be authenticated)
    if request.args.get('forPage') == '/dashboard':
        capability.allow_client_incoming('support_agent')
    else:
        # Otherwise we give them a name of "customer"
        capability.allow_client_incoming('customer')

    # Generate the capability token
    token = capability.generate()

    return jsonify({'token': token})


@app.route('/support/call', methods=['POST'])
def call():
    """Returns TwiML instructions to Twilio's POST requests"""
    response = twiml.Response()

    with response.dial(callerId=app.config['TWILIO_NUMBER']) as dial:
        # If the browser sent a phoneNumber param, we know this request
        # is a support agent trying to call a customer's phone
        if 'phoneNumber' in request.form:
            dial.number(request.form['phoneNumber'])
        else:
            # Otherwise we assume this request is a customer trying
            # to contact support from the home page
            dial.client('support_agent')

    return str(response)
````

This is the modified code utilizing the package from previous version of the twilio package. This work for me. 

Also if you are interested you can include the missing method in the latest twilio package by including the following method inside the "**ClientCompatabilityToken**" class
```
def generate(self, expires=3600):
    """Generate a valid JWT token with an expiration date.

    :param int expires: The token lifetime, in seconds. Defaults to
                        1 hour (3600)

    """
    payload = self._generate_payload()
    payload['iss'] = self.account_sid
    payload['exp'] = int(time.time() + expires)
    jwt = Jwt(secret_key="")
    return jwt.encode(payload, self.auth_token)
```

**Comment by franzi31** [comment]
Hi Kannan, 
If you prefer not to downgrade to the older version of the twilio package, using something like this worked for me.  However, I have also run into several other bugs with the newer twilio package.

def get_token():
    # get credentials for environment variables
    account_sid = os.environ['TWILIO_ACCOUNT_SID']
    auth_token = os.environ['TWILIO_AUTH_TOKEN']
    application_sid = os.environ['TWILIO_TWIML_APP_SID']
    identity = 'someone'
      
    capability = ClientCapabilityToken(account_sid, auth_token, ttl = 24*60*60)
    capability.allow_client_outgoing(application_sid)
    capability.allow_client_incoming(identity)
    token = capability.to_jwt()
    token = str(token,'utf-8') #convert to string
    return {'identity': identity, 'token': token }

**Comment by franzi31** [comment]
apologies for the formatting error in the previous message.  it should just be:
def get_token():
  # get credentials for environment variables
  account_sid = os.environ['TWILIO_ACCOUNT_SID']
  auth_token = os.environ['TWILIO_AUTH_TOKEN']
  application_sid = os.environ['TWILIO_TWIML_APP_SID']
  identity = 'someone'
  capability = ClientCapabilityToken(account_sid, auth_token, ttl = 24*60*60)
  capability.allow_client_outgoing(application_sid)
  capability.allow_client_incoming(identity)
  token = capability.to_jwt()
  token = str(token,'utf-8') #convert to string
  return {'identity': identity, 'token': token }

**Comment by franzi31** [comment]
apologies for the formatting error, it should be

def get_token():
    # get credentials for environment variables
    account_sid = os.environ['TWILIO_ACCOUNT_SID']
    auth_token = os.environ['TWILIO_AUTH_TOKEN']
    application_sid = os.environ['TWILIO_TWIML_APP_SID']
    identity = 'someone'  
    capability.allow_client_outgoing(application_sid)
    capability.allow_client_incoming(identity)
    token = capability.to_jwt()
    token = str(token,'utf-8')
    return {'identity': identity, 'token': token }
